site_name: Open Network Fabric
site_url: https://docs.hedgehog.cloud/
site_description: Hedgehog Open Network Fabric Documentation
site_author: Hedgehog Authors
copyright:
  Copyright &copy; 2025 Hedgehog
  &#x25cf;
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  logo: assets/logo.webp
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.sections
    # - navigation.tabs # TODO Do we need them or just everything in the sidebar is better?
    # we can hide sidebars for the tabs where it's not needed
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars
    - navigation.expand
    - toc.follow
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started:
          - Overview: tutorial/getting-started.md
          - Download CLI: getting-started/download.md
          - Deploy Your First Virtual Lab: tutorial/getting-started-lab.md
      - Demo Lab: tutorial/demo-lab.md
      - Running VLAB: tutorial/running-vlab.md
  - How-to Guides:
      - Getting Started:
      - Deploying:
          - Deploying CLI: how-to/deploying-cli.md
          - Deploying Fabric: how-to/deploying-fabric.md
          - Fabric CLI: how-to/deploying-fabric-cli.md
      - External Connectivity: how-to/add-external-connectivity.md 
      - Device Management: 
          - Device Replacement: how-to/device-replacement.md
          - Power Reset Switch: how-to/power-reset-switch.md
      - Maintenance:
          - Upgrading Fabric: how-to/upgrading-fabric.md
          - Troubleshooting: how-to/troubleshooting-fabric.md
      - Documentation: how-to/preview-docs-locally.md
  - Explanation:
      - Concepts: concepts/concepts-overview.md
      - Troubleshooting: troubleshooting/overview.md
      - Architecture:
          - Overview: architecture/overview.md
          - Hedgehog Network Fabric: architecture/fabric.md
      - User Guide:
          - Overview: user-guide/overview.md
          - Devices: user-guide/devices.md
          - Profiles: user-guide/profiles.md
          - VPCs: user-guide/vpcs.md
          - Connections: user-guide/connections.md
          - External Connectivity: user-guide/external.md
          - Shrink & Expand: user-guide/shrink-expand.md
          - Grafana: user-guide/grafana.md
      - Profiles & Devices: explanation/profiles-devices.md
      - VPC Peering and Isolation: explanation/vpc-peering.md
      - Security Model: explanation/security-model.md
  - Reference:
      - Fabric API: reference/fabric-api.md
      - Fabric CLI: reference/fabric-cli.md
      - CLI Commands: reference/cli.md
      - Profiles: reference/profiles.md
      - Supported Devices: reference/supported-devices.md
      - Release Notes: reference/release-notes.md
      - Releases: reference/releases.md
  - Installation & Upgrade:
      - Requirements: install-upgrade/requirements.md
      - Installation: install-upgrade/install.md
      - Configuration: install-upgrade/config.md
      - Upgrade: install-upgrade/upgrade.md
      - Build & Wiring: install-upgrade/build-wiring.md
      - Supported Devices: install-upgrade/supported-devices.md
  - Known Limitations: known-limitations/known-limitations.md
  - Release Notes:
      - Overview: release-notes/index.md
  - VLAB:
      - Overview: vlab/overview.md
      - Running VLAB: vlab/running.md
      - Demo: vlab/demo.md
  - FAQ: faq/overview.md
  - Contributing: contribute/docs.md

extra:
  homepage: https://docs.hedgehog.cloud
  version:
    provider: mike
    default: latest
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
       - manage
       - accept
       - reject
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: GitHub
        checked: false
  analytics:
    provider: google
    property: G-NZSPQEJNFH

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/githedgehog/

repo_url: https://github.com/githedgehog/docs
repo_name: githedgehog/docs
# edit_uri: edit/master/docs/

plugins:
  - search
  - glightbox
  - autorefs
  - awesome-pages:
      collapse_single_pages: true
      sort_type: natural
      order_by: title
  - git-revision-date-localized:
      enable_creation_date: true
      # - htmlproofer # https://github.com/manuzhang/mkdocs-htmlproofer-plugin

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

watch:
  - includes
  - overrides
